name = "Windows"
category_ordering = [
  "Security",
  "Windows Firewall"
]
info = "Edit this to say something meaningful about Windows. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec feugiat metus, non placerat ex. Quisque consectetur purus non mollis placerat."