#This is the template for What2Log Tools entries

# Meta data about this App entry
title = "Test Tool 4"
author = "Sebastian Boutin Blomfield"
credits = []
release.date = 2021-05-21
release.version = 0.1

# About this app
operating_system = ["Linux Ubuntu"]
default_installed = true #True or false only

#Installation Info (install info is optional, some tools are part of base os)
[[app.install]]
txt = """
Install the tool by doing some stuff in Linux.

Totally legit installation instructions"""
img = "img1.png"
#continue as necessary

# App Info
[[app.info]]
txt = """
This is a fake page about an imaginary Linux tool
"""
img = "img1.png"
#continue as necessary
