#This is the template for What2Log Tools entries

# Meta data about this App entry
title = "Test Tool 3"
author = "Sebastian Boutin Blomfield"
credits = []
release.date = 2021-05-21
release.version = 0.1

# About this app
operating_system = ["Windows 10 Professional"]
default_installed = true #True or false only

#Installation Info (install info is optional, some tools are part of base os)
[[app.install]]
txt = """
Install the tool by doing some stuff in Windows.

Totally legit installation instructions"""
img = "img1.png"
#continue as necessary

# App Info
[[app.info]]
txt = """
This would be a really neat tool if it were real
"""
img = "img1.png"

[[app.info]]
txt = """
But this is actually just a test
"""
img = "img2.png"
#continue as necessary