name = "Flynn Weeks"
icon = "authors/flynn-weeks.jpg"
organization = "InfoSec Innovations"
bio.en = """
Security Specialist at ISI and creative mind behind What2Log. I generate most
of the content on the site and am in charge of the project as a whole. In my free time
I show and breed Cavaliers, game, and garden."""
