name = "Flynn Weeks"
icon = "authors/flynn-weeks.png"
organization = "InfoSec Innovations"
bio.en = """
Security Specialist at ISI and creative mind behing What2Log. I generate most
of the sites content and am in charge of the project as a whole. In my free time
I show and breed Cavaliers, game, and garden."""
