name = "Sebastian Boutin Blomfield"
icon = "images/authors/sebastian-blomfield.jpg"
bio = """Half French, half English guy who mostly works with web technologies at InfoSec Innovations.\
I started off programming for video games, and then got into the idea of web games, \
and now I build stuff using JavaScript (which contrary to popular opinion, I don't hate). \
I'm also a musician when I'm not doing programming related stuff."""