name = "Sebastian Boutin Blomfield"
icon = "authors/sebastian-blomfield.jpg"
organization = "InfoSec Innovations"
bio.en = """
Half French, half English guy who mostly works with web technologies.\
I started off programming for video games, and then got into the idea of web games, \
and now I build stuff using JavaScript (which contrary to popular opinion, I don't hate). \
I'm also a musician when I'm not doing programming related stuff."""